spring.application.name=video-service
server.port=8090 
spring.datasource.url=jdbc:h2:mem:video-db 
spring.h2.console.enabled=true 
spring.graphql.graphiql.enabled=true 
spring.security.user.name=admin
spring.security.user.password=admin
spring.graphql.websocket.path=/graphql